spring:
  application:
    name: REPORTING-SERVICE
  datasource:
    url : ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/reportingDb?createDatabaseIfNotExist=true}
    username : ${SPRING_DATASOURCE_USERNAME:root}
    password : ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      max-lifetime: 1800000       # 30 min
      idle-timeout: 600000        # 10 min
      keepalive-time: 300000      # 5 min
  jpa :
    hibernate :
      ddl-auto : update
server:
  port: ${SERVER_PORT:8090}