name: Docker Build and Push

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  NODE_VERSION: "20"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        service:
          - name: pos-system
            path: frontend/pos-system
            dockerfile: frontend/pos-system/Dockerfile
          - name: user-website
            path: frontend/user-website
            dockerfile: frontend/user-website/Dockerfile
          - name: product-service
            path: services/product-service
            dockerfile: services/product-service/Dockerfile
          - name: user-service
            path: services/user-service
            dockerfile: services/user-service/Dockerfile
          - name: outlet-service
            path: services/outlet-service
            dockerfile: services/outlet-service/Dockerfile
          - name: reporting-service
            path: services/reporting-service
            dockerfile: services/reporting-service/Dockerfile
          - name: discovery-service
            path: services/discovery-service
            dockerfile: services/discovery-service/Dockerfile
          - name: api-gateway
            path: services/api-gateway
            dockerfile: services/api-gateway/Dockerfile
          - name: bff
            path: bff
            dockerfile: bff/Dockerfile

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service.name }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ matrix.service.path }}
        file: ${{ matrix.service.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service.name }}:${{ github.sha }}
        format: spdx-json
        output-file: sbom-${{ matrix.service.name }}.spdx.json

    - name: Upload SBOM
      uses: actions/upload-artifact@v3
      with:
        name: sbom-${{ matrix.service.name }}
        path: sbom-${{ matrix.service.name }}.spdx.json
